### ISSUE TITLE
Swift 6 Compatibility

### ISSUE THREAD

**Issue by orchetect** [mtynior/ColorizeSwift#13]
Swift 6 (Xcode 16) adds new requirements for concurrency, and it looks like ColorizeSwift will need some modifications to satisfy them.

One such example is the global static variables. It's not possible to use them without a compiler error.

<img width="831" alt="error" src="https://github.com/user-attachments/assets/03fd577c-fab5-4266-8944-eac03871ff94">

**Comment by mtynior** [comment]
Hi,

Thanks for reporting this. I've fixed it in [this PR](https://github.com/mtynior/ColorizeSwift/pull/14). However, in the future, I will probably deprecate the `String.isColorizedEnabled` property as this is reported as unsafe from Swift 6.

For now, the new code is available in version 1.7.0.

**Comment by orchetect** [comment]
Works! Brilliant. Tested in Xcode 16 with Swift 6.0.
