### ISSUE TITLE
Update to v4 of package format

### ISSUE THREAD

**Issue by ghost** [mtynior/ColorizeSwift#3]
When adding this to my `Package.swift` manifest, using `swift-tools-version:4.2`, when I update, I get the following warning:

```
warning: PackageDescription API v3 is deprecated and will be removed in the future; used by package(s): ColorizeSwift
```

The documentation for how to add this as a package also appears to use v3 format.

Can this all be updated to v4 please?

**Comment by mtynior** [comment]
how your` Package.swift `looks like? Is this code working fine following version properly?

**Comment by mtynior** [comment]
How does your `Package.swift` look like? Is the following code working?

```
let package = Package(
    name: "YourApp",
    products: [
        .executable(name: "tool",  targets: ["tool"])
],
    dependencies: [
        .package(url: "https://github.com/mtynior/ColorizeSwift", from: "1.0.0")
    ],
    targets: [
        .target(name: "tool", dependencies: ["ColorizeSwift" ])
    ]
)
```

**Comment by ghost** [comment]
That looks right for updating how to add it as a package; the manifest of the package itself also apparently needs to be updated to v4.

**Comment by mtynior** [comment]
Base on [this](https://github.com/apple/swift-package-manager/blob/master/Documentation/PackageDescriptionV4.md), the library should be compatible with the minimal version of the v4 manifest.

**Comment by ghost** [comment]
Strange. It's still giving me the warning about the manifest still being in v3.

**Comment by mtynior** [comment]
Maybe it is complaining about the code. The library has not been updated to Swift 4.x.

**Comment by ghost** [comment]
Hm. Possibly.

**Comment by mtynior** [comment]
Right now I don't have time to investigate this issue, maybe after Christmas. If this is something you can solve on your own, I'm more than happy to merge the pull request.

**Comment by ghost** [comment]
I'll see what I can do

**Comment by noahbass** [comment]
> Base on [this](https://github.com/apple/swift-package-manager/blob/master/Documentation/PackageDescriptionV4.md), the library should be compatible with the minimal version of the v4 manifest.

@mtynior I think this is just the requirement for the manifest to be valid, but in order to use the package as a dependency, other fields must be specified.

I did some tests and found that this format works for the Package.swift file (tested using `swift build` and using the package as a dependency in another package):

```swift
// swift-tools-version:4.2
import PackageDescription

let package = Package(
    name: "ColorizeSwift",
    products: [
        .library(name: "ColorizeSwift", targets: ["ColorizeSwift"]),
    ],
    targets: [
        .target(name: "ColorizeSwift", path: "Source"),
    ]
)
```

This change would likely require a major version tag bump due to the swift 4 specific code.

(Running Swift 4.2.1, macOS 10.14.2)
