### ISSUE TITLE
No TerminalColor.cyan option

### ISSUE THREAD

**Issue by DeeGeeMan** [mtynior/ColorizeSwift#9]
There is no ```cyan``` in the TerminalColor enum.  

The current ```cyan1```, ```cyan2```, and ```cyan3``` doesn't match the ```cyan()``` function color.

**Comment by mtynior** [comment]
I would try the `aqua`, I think it is the closest to the original cyan color. I know the names from the 256 color palette might be confusing, so I would look at [this list](https://github.com/mtynior/ColorizeSwift/blob/master/Assets/256Colors.png).
